#!/system/bin/sh


### zRam Settings ###
# 1 to enable zRam
# 0 to disable zRam (default)

ZRAM=1

#if zRam enabled, enter size of zRam in MB (default is 100MB)

DISK_SIZE=100


#set zram

if [ $ZRAM = "1" ]; then
	SWAPCHECK=`cat /proc/swaps | grep zram0`;
	if [ -z "$SWAPCHECK" ]; then
		echo 1 > /sys/block/zram0/reset;
		echo $(($DISK_SIZE*1024*1024)) > /sys/block/zram0/disksize;
		mkswap /dev/block/zram0;
		swapon /dev/block/zram0;
	fi
#	chmod 666 /sys/module/lowmemorykiller/parameters/minfree;
#	echo "2048,2560,3072,6144,10240,15360" > /sys/module/lowmemorykiller/parameters/minfree;
#	echo 80 > /proc/sys/vm/swappiness;
fi

if [ $ZRAM = "0" ]; then
	SWAPCHECK=`cat /proc/swaps | grep zram0`;
	if [ -n "$SWAPCHECK" ]; then
		swapoff /dev/block/zram0 >/dev/null 2>&1;
		echo 1 > /sys/block/zram0/reset;
	fi
fi

exit 0
