#!/system/bin/sh
# Jarvis Ultimate Edition

busybox echo "Bacem Tweak Voltage Information"
busybox echo "Status of voltage:"
busybox grep -i mV ./proc/sys/bacem/volt/cpu
busybox echo "0mv is not in undervolt mode"
busybox echo "Voltage :"
busybox grep -i 0 ./sys/class/regulator/regulator.5/microvolts
busybox echo "Default voltage 832mhz = 1300000"
busybox echo "Default voltage 312mhz = 1240000"
busybox echo "Bacem Tweak from irfanbagus@xda" 
busybox echo "Script by: savie-xda"
busybox echo "Diedit Kembali Oleh: Afrizal Firmansyah @ Xda"
